# Generated by Django 3.0.4 on 2020-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('urlposter', models.CharField(max_length=100)),
                ('urlbackdrop', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('score', models.FloatField()),
            ],
        ),
    ]
