# Generated by Django 3.0.4 on 2020-05-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='actor',
            field=models.CharField(max_length=500),
        ),
    ]
